//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cm_CustomerAuthenticators
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cm_CustomerAuthenticators()
        {
            this.Cm_CustomerInterviews = new HashSet<Cm_CustomerInterviews>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Name { get; set; }
        public string Gsm { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public Nullable<int> CustomerLocationId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeleterId { get; set; }
        public Nullable<System.DateTime> DeleterDate { get; set; }
    
        public virtual Cm_Customer Cm_Customer { get; set; }
        public virtual Gn_User Gn_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerInterviews> Cm_CustomerInterviews { get; set; }
    }
}
