//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cm_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cm_Customer()
        {
            this.Cm_CustomerAuthenticators = new HashSet<Cm_CustomerAuthenticators>();
            this.Cm_CustomerLocations = new HashSet<Cm_CustomerLocations>();
            this.Cm_CustomerMachineparks = new HashSet<Cm_CustomerMachineparks>();
            this.Cm_CustomerRequest = new HashSet<Cm_CustomerRequest>();
            this.Cm_CustomerSalesmans = new HashSet<Cm_CustomerSalesmans>();
            this.Cm_MachineparkRental = new HashSet<Cm_MachineparkRental>();
        }
    
        public int Id { get; set; }
        public string TaxOffice { get; set; }
        public string TaxNumber { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> IsHasel { get; set; }
        public string NetsisRentliftCode { get; set; }
        public string NetsisHaselCode { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string Web { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsRental { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerAuthenticators> Cm_CustomerAuthenticators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerLocations> Cm_CustomerLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerMachineparks> Cm_CustomerMachineparks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerRequest> Cm_CustomerRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerSalesmans> Cm_CustomerSalesmans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_MachineparkRental> Cm_MachineparkRental { get; set; }
    }
}
