//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cm_CustomerMachineparks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cm_CustomerMachineparks()
        {
            this.Cm_MachineparkRental = new HashSet<Cm_MachineparkRental>();
        }
    
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int OwnerId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> MarkId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> ManufactureYear { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int Quantity { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> RefRowId { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    
        public virtual Cm_Customer Cm_Customer { get; set; }
        public virtual Cm_CustomerLocations Cm_CustomerLocations { get; set; }
        public virtual Cm_CustomerRequest Cm_CustomerRequest { get; set; }
        public virtual Cm_MachineparkCategory Cm_MachineparkCategory { get; set; }
        public virtual Cm_MachineparkMark Cm_MachineparkMark { get; set; }
        public virtual Gn_User Gn_User { get; set; }
        public virtual Gn_User Gn_User1 { get; set; }
        public virtual Gn_User Gn_User2 { get; set; }
        public virtual Pr_MachineModel Pr_MachineModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_MachineparkRental> Cm_MachineparkRental { get; set; }
    }
}
