//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cm_MachineparkCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cm_MachineparkCategory()
        {
            this.Cm_CustomerMachineparks = new HashSet<Cm_CustomerMachineparks>();
            this.Cm_CustomerRequest = new HashSet<Cm_CustomerRequest>();
        }
    
        public int Id { get; set; }
        public int ParentId { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public bool IsRequestVisible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerMachineparks> Cm_CustomerMachineparks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerRequest> Cm_CustomerRequest { get; set; }
    }
}
