//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_AreaCity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gn_AreaCity()
        {
            this.Gn_AreaCityRegions = new HashSet<Gn_AreaCityRegions>();
        }
    
        public int Id { get; set; }
        public string CityName { get; set; }
        public int PlateCode { get; set; }
        public string PhonePrefix { get; set; }
    
        public virtual Gn_AreaCity Gn_AreaCity1 { get; set; }
        public virtual Gn_AreaCity Gn_AreaCity2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gn_AreaCityRegions> Gn_AreaCityRegions { get; set; }
    }
}
