//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_AreaCityRegions
    {
        public int Id { get; set; }
        public Nullable<int> CityId { get; set; }
        public string RegionName { get; set; }
    
        public virtual Gn_AreaCity Gn_AreaCity { get; set; }
    }
}
