//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_Combos
    {
        public int Id { get; set; }
        public int ComboTypeId { get; set; }
        public int Key { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    
        public virtual Gn_ComboTypes Gn_ComboTypes { get; set; }
    }
}
