//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_Control
    {
        public int Id { get; set; }
        public Nullable<int> ModulId { get; set; }
        public Nullable<int> PageId { get; set; }
        public string ControlId { get; set; }
        public string ControlTypeName { get; set; }
        public string ControlText { get; set; }
        public string ControlTextEng { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
