//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_ModulsAndMenus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gn_ModulsAndMenus()
        {
            this.Gn_Notifications = new HashSet<Gn_Notifications>();
        }
    
        public int Id { get; set; }
        public int LinkedModulId { get; set; }
        public int ParentId { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> PageId { get; set; }
        public string PageName { get; set; }
        public int IndexOrder { get; set; }
        public string IconName { get; set; }
        public string PageSeofriendlyName { get; set; }
        public string PageNameText { get; set; }
        public string PageNameTextEng { get; set; }
        public string PageDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gn_Notifications> Gn_Notifications { get; set; }
    }
}
