//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gn_User()
        {
            this.Cm_CustomerAuthenticators = new HashSet<Cm_CustomerAuthenticators>();
            this.Cm_CustomerInterviews = new HashSet<Cm_CustomerInterviews>();
            this.Cm_CustomerInterviews1 = new HashSet<Cm_CustomerInterviews>();
            this.Cm_CustomerInterviews2 = new HashSet<Cm_CustomerInterviews>();
            this.Cm_CustomerInterviews3 = new HashSet<Cm_CustomerInterviews>();
            this.Cm_CustomerLocations = new HashSet<Cm_CustomerLocations>();
            this.Cm_CustomerMachineparks = new HashSet<Cm_CustomerMachineparks>();
            this.Cm_CustomerMachineparks1 = new HashSet<Cm_CustomerMachineparks>();
            this.Cm_CustomerMachineparks2 = new HashSet<Cm_CustomerMachineparks>();
            this.Cm_CustomerRequest = new HashSet<Cm_CustomerRequest>();
            this.Cm_CustomerRequest1 = new HashSet<Cm_CustomerRequest>();
            this.Cm_CustomerRequest2 = new HashSet<Cm_CustomerRequest>();
            this.Cm_CustomerRequest3 = new HashSet<Cm_CustomerRequest>();
            this.Cm_CustomerRequest4 = new HashSet<Cm_CustomerRequest>();
            this.Cm_CustomerSalesmans = new HashSet<Cm_CustomerSalesmans>();
            this.Cm_CustomerSalesmans1 = new HashSet<Cm_CustomerSalesmans>();
            this.Cm_MachineparkRental = new HashSet<Cm_MachineparkRental>();
            this.Cm_MachineparkRental1 = new HashSet<Cm_MachineparkRental>();
            this.Cm_MachineparkRental2 = new HashSet<Cm_MachineparkRental>();
            this.Gn_Notifications = new HashSet<Gn_Notifications>();
            this.Gn_Notifications1 = new HashSet<Gn_Notifications>();
            this.Gn_UserRoles = new HashSet<Gn_UserRoles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string Gsm { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerAuthenticators> Cm_CustomerAuthenticators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerInterviews> Cm_CustomerInterviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerInterviews> Cm_CustomerInterviews1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerInterviews> Cm_CustomerInterviews2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerInterviews> Cm_CustomerInterviews3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerLocations> Cm_CustomerLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerMachineparks> Cm_CustomerMachineparks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerMachineparks> Cm_CustomerMachineparks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerMachineparks> Cm_CustomerMachineparks2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerRequest> Cm_CustomerRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerRequest> Cm_CustomerRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerRequest> Cm_CustomerRequest2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerRequest> Cm_CustomerRequest3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerRequest> Cm_CustomerRequest4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerSalesmans> Cm_CustomerSalesmans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_CustomerSalesmans> Cm_CustomerSalesmans1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_MachineparkRental> Cm_MachineparkRental { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_MachineparkRental> Cm_MachineparkRental1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cm_MachineparkRental> Cm_MachineparkRental2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gn_Notifications> Gn_Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gn_Notifications> Gn_Notifications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gn_UserRoles> Gn_UserRoles { get; set; }
    }
}
