//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_UserRights
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ModulId { get; set; }
        public Nullable<bool> RecordInsert { get; set; }
        public Nullable<bool> RecordEdit { get; set; }
        public Nullable<bool> RecordShow { get; set; }
        public Nullable<bool> RecordDelete { get; set; }
        public string CreatorName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifierName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
