//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gn_UserRoles
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> DepartmentRuleId { get; set; }
    
        public virtual Gn_Area Gn_Area { get; set; }
        public virtual Gn_DepartmentRoles Gn_DepartmentRoles { get; set; }
        public virtual Gn_User Gn_User { get; set; }
    }
}
