//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Cm_CustomerSalesmans
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> SalesmanId { get; set; }
        public Nullable<int> CRGID { get; set; }
        public Nullable<bool> Flag { get; set; }
        public string CreatorName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifierName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeleterId { get; set; }
        public Nullable<System.DateTime> DeleterDate { get; set; }
    }
}
