//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Cm_CustomerInterviews
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> AuthenticatorId { get; set; }
        public int InterviewTypeId { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<System.DateTime> PlannedInterviewDate { get; set; }
        public string Note { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> DeleterId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ImportantId { get; set; }
    }
}
