//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Cm_CustomerMachineparks
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int OwnerId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> MarkId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> ManufactureYear { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public int Quantity { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> RefRowId { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
