//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Cm_CustomerRequest
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> MarkId { get; set; }
        public Nullable<int> ModelId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int SalesType { get; set; }
        public Nullable<System.DateTime> EstimatedBuyDate { get; set; }
        public Nullable<int> UseDuration { get; set; }
        public Nullable<int> UseDurationUnit { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public int ChannelId { get; set; }
        public Nullable<int> SalesmanId { get; set; }
        public Nullable<short> ConditionType { get; set; }
        public Nullable<int> MonthlyWorkingHours { get; set; }
        public int ResultType { get; set; }
        public bool IsDeleted { get; set; }
        public int CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Note { get; set; }
    }
}
