//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Cm_Customer
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Id { get; set; }
        public string TaxOffice { get; set; }
        public string TaxNumber { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> IsHasel { get; set; }
        public string NetsisRentliftCode { get; set; }
        public string NetsisHaselCode { get; set; }
        public Nullable<int> SectorId { get; set; }
        public string Web { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public bool IsRental { get; set; }
    }
}
