//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log_Cm_CustomerAuthenticators
    {
        public int LogId { get; set; }
        public System.DateTime LogDate { get; set; }
        public int Id { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> ModifierId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Name { get; set; }
        public string Gsm { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public Nullable<int> CustomerLocationId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DeleterId { get; set; }
        public Nullable<System.DateTime> DeleterDate { get; set; }
    }
}
