//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Dochuman
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCH_KULLANICIBOLGE
    {
        public int Id { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> WFState { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> SUBEKODU { get; set; }
        public string BOLGE { get; set; }
        public Nullable<bool> ITHALATISKONTOSUGORSUN { get; set; }
        public string DEPARTMAN { get; set; }
        public string GRUP { get; set; }
        public Nullable<bool> SOZLESMEYETKI { get; set; }
        public Nullable<int> RAPOR_AY { get; set; }
        public Nullable<int> RAPOR_YIL { get; set; }
        public Nullable<bool> SOZLESMEFIRMA { get; set; }
        public string USER_TEL { get; set; }
        public string USER_FAX { get; set; }
        public string SIPARISYETKIGRUP { get; set; }
        public Nullable<bool> ASISTAN { get; set; }
        public Nullable<bool> KIRASEVKISLEYEBILIR { get; set; }
        public Nullable<bool> HAREKETEKRANI { get; set; }
        public Nullable<bool> KIRASEVKONAY2 { get; set; }
        public Nullable<bool> KIRASATICISECER { get; set; }
        public string PLASIYERKODU { get; set; }
        public string ANABOLGE { get; set; }
        public Nullable<bool> SATICI { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public Nullable<bool> SATINALMAONAYLAR { get; set; }
        public Nullable<bool> EFATURATUMKAYITLAR { get; set; }
        public Nullable<bool> SERBESTBOLGE { get; set; }
        public Nullable<bool> SATINALMATUMBOLGE { get; set; }
        public Nullable<int> ENKULID { get; set; }
        public Nullable<bool> EFATURAGELENKAYITLAR { get; set; }
        public Nullable<bool> TEKLIFGOREBILIR { get; set; }
        public Nullable<bool> CARIGOREBILIR { get; set; }
        public Nullable<bool> FARKLILOKASYONSEVK { get; set; }
        public Nullable<bool> ISM_CARIONAY { get; set; }
        public Nullable<bool> ITHISKGORUR { get; set; }
        public Nullable<bool> ZIYARETGOREBILIR { get; set; }
        public Nullable<bool> BOLGEKAYITLARIGOREBILIR { get; set; }
        public Nullable<int> OneId { get; set; }
    }
}
