//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Dochuman
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCH_SEKTOR
    {
        public int Id { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> WFState { get; set; }
        public string SEKTORACIKLAMA { get; set; }
        public string GRUP { get; set; }
        public string KOD { get; set; }
        public string SEKTOR { get; set; }
        public string ALTSEKTOR { get; set; }
    }
}
