//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Dochuman
{
    using System;
    using System.Collections.Generic;
    
    public partial class DCV_KULLANICIBOLGE
    {
        public int Id { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> WFState { get; set; }
        public Nullable<int> USERID { get; set; }
        public string KULLANICI { get; set; }
        public Nullable<byte> KILIT { get; set; }
        public string WindowsName { get; set; }
        public string Title { get; set; }
        public string EMailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<byte> RunTimeAdmin { get; set; }
        public string SUBE { get; set; }
        public string GRUP { get; set; }
        public string BOLGE { get; set; }
        public string ANABOLGE { get; set; }
        public string DEPARTMAN { get; set; }
        public string BOLGE_KS { get; set; }
        public string PLASIYERKODU { get; set; }
        public Nullable<bool> AKTIF { get; set; }
        public Nullable<bool> SATICI { get; set; }
        public Nullable<int> SUBEKODU { get; set; }
        public string SUBESEC { get; set; }
        public Nullable<int> ENKULID { get; set; }
    }
}
