//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Dochuman
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSL_LOKASYON
    {
        public int Id { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> WFState { get; set; }
        public string LOK_ADI { get; set; }
        public string LOK_ADRES { get; set; }
        public string LOK_IL { get; set; }
        public string LOK_ILCE { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string LOK_TEL { get; set; }
        public string LOK_FAX { get; set; }
        public Nullable<bool> LOK_FAT { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OneId { get; set; }
    
        public virtual HSL_CARI HSL_CARI { get; set; }
    }
}
