//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Dochuman
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSL_YETKILI
    {
        public int Id { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> WFState { get; set; }
        public Nullable<int> MasterId { get; set; }
        public string YETKILI_ADI { get; set; }
        public string YETKILI_GSM { get; set; }
        public string YETKILI_TEL1 { get; set; }
        public string YETKILI_TEL2 { get; set; }
        public string YETKILI_FAX { get; set; }
        public string YETKILI_EMAIL { get; set; }
        public string YETKILI_UNVAN { get; set; }
        public Nullable<int> YETKILI_LOKID { get; set; }
        public Nullable<bool> YETKILI_NAKLIYE { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OneId { get; set; }
    
        public virtual HSL_CARI HSL_CARI { get; set; }
    }
}
