//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Dochuman
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSL_CARI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HSL_CARI()
        {
            this.HSL_LOKASYON1 = new HashSet<HSL_LOKASYON>();
            this.HSL_YETKILI = new HashSet<HSL_YETKILI>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<byte> WFState { get; set; }
        public string HSL_CARIKOD { get; set; }
        public string HSL_VD { get; set; }
        public string HSL_VN { get; set; }
        public string HSL_CARIISIM { get; set; }
        public string HSL_KISALTMA { get; set; }
        public string HSL_FIRMA { get; set; }
        public string HSL_CARIKODO { get; set; }
        public string HSL_CARIKODH { get; set; }
        public Nullable<int> HSL_SATID { get; set; }
        public Nullable<int> HSL_SATID2 { get; set; }
        public string HSL_LOKASYON { get; set; }
        public string HSL_CLASS { get; set; }
        public Nullable<int> HSL_SEKTORID { get; set; }
        public Nullable<int> HSL_SID { get; set; }
        public Nullable<int> HSL_KID { get; set; }
        public string HSL_WEB { get; set; }
        public Nullable<int> HSL_SSATID { get; set; }
        public Nullable<int> HSL_SSATID2 { get; set; }
        public string HSL_DURUM { get; set; }
        public Nullable<bool> HSL_ANACARI { get; set; }
        public string HSL_GRUP { get; set; }
        public Nullable<int> HSL_MAKINESAY { get; set; }
        public Nullable<int> HSL_SATICI { get; set; }
        public Nullable<int> HSL_TFORKLIFTSAYISI { get; set; }
        public Nullable<int> HSL_HFORKLIFTSAYISI { get; set; }
        public Nullable<int> HSL_SATICILINDE { get; set; }
        public Nullable<int> HSL_SATICICOMBILIFT { get; set; }
        public Nullable<int> HSL_SATICIMANLIFT { get; set; }
        public Nullable<int> HSL_COMBILIFTSAYISI { get; set; }
        public Nullable<int> HSL_MANLIFTSAYISI { get; set; }
        public Nullable<int> HSL_JLGSAYISI { get; set; }
        public Nullable<int> HSL_FORKLIFTSAYISI { get; set; }
        public Nullable<int> HSL_LINDESAYISI { get; set; }
        public Nullable<int> HSL_ISMAKSAYISI { get; set; }
        public Nullable<int> HSL_KOBELCOSAYISI { get; set; }
        public Nullable<int> HSL_TEREXSAYISI { get; set; }
        public Nullable<int> OneId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HSL_LOKASYON> HSL_LOKASYON1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HSL_YETKILI> HSL_YETKILI { get; set; }
    }
}
