//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL_Dochuman
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSV_CASABIT
    {
        public string SIRKET { get; set; }
        public string CARI_KOD { get; set; }
        public string CARI_TEL { get; set; }
        public string FAX { get; set; }
        public string CARI_ISIM { get; set; }
        public string VERGI_DAIRESI { get; set; }
        public string VERGI_NUMARASI { get; set; }
        public string CARI_ADRES { get; set; }
        public string CARI_IL { get; set; }
        public string CARI_ILCE { get; set; }
        public Nullable<short> VADE_GUNU { get; set; }
        public string CKOD { get; set; }
        public string KILIT { get; set; }
        public Nullable<decimal> CM_BORCT { get; set; }
        public Nullable<decimal> CM_ALACT { get; set; }
        public Nullable<decimal> BAKIYE { get; set; }
    }
}
